export const SHOW_LOADING = 'SHOW_LOADING';
export const HIDE_LOADING = 'HIDE_LOADING';

export const SHOW_SEARCHBAR = 'SHOW_SEARCHBAR';
export const HIDE_SEARCHBAR = 'HIDE_SEARCHBAR';

export const SET_ISLOGIN = 'SET_ISLOGIN';
export const SET_ISNOTLOGIN = 'SET_ISNOTLOGIN';

export const FETCH_USER = 'FETCH_USER';
export const FETCH_USER_SUCCESS = 'FETCH_USER_SUCCESS';
export const FETCH_USER_FAILED = 'FETCH_USER_FAILED';

export const FETCH_COURSE_LIST = 'FETCH_COURSE_LIST';
export const FETCH_COURSE_LIST_SUCCESS = 'FETCH_COURSE_LIST_SUCCESS';
export const FETCH_COURSE_LIST_FAILED = 'FETCH_COURSE_LIST_FAILED';

export const FETCH_SUBJECT_LIST = 'FETCH_SUBJECT_LIST';
export const FETCH_SUBJECT_LIST_SUCCESS = 'FETCH_SUBJECT_LIST_SUCCESS';
export const FETCH_SUBJECT_LIST_FAILED = 'FETCH_SUBJECT_LIST_FAILED';